DROP TABLE IF EXISTS entidades;

CREATE TABLE entidades (
    CO_ENTIDADE INTEGER PRIMARY KEY,
    NO_MUNICIPIO TEXT,
    NO_ENTIDADE TEXT NOT NULL,
    SG_UF TEXT,
    QT_MAT_BAS INTEGER,
    QT_MAT_INF INTEGER,
    QT_MAT_FUND INTEGER,
    QT_MAT_MED INTEGER,
    QT_MAT_MED_CT INTEGER,
    QT_MAT_MED_NM INTEGER,
    QT_MAT_PROF INTEGER,
    QT_MAT_PROF_TEC INTEGER,
    QT_MAT_EJA INTEGER,
    QT_MAT_ESP INTEGER
);