DROP TABLE IF EXISTS entidades;
DROP TABLE IF EXISTS tb_usuario;

CREATE TABLE entidades (
    CO_ENTIDADE INTEGER,
    NO_ENTIDADE TEXT,
    NO_UF TEXT,
    SG_UF TEXT,
    CO_UF INTEGER,
    NO_MUNICIPIO TEXT,
    CO_MUNICIPIO INTEGER,
    NO_MESORREGIAO TEXT,
    CO_MESORREGIAO INTEGER,
    NO_MICRORREGIAO TEXT,
    CO_MICRORREGIAO INTEGER,
    NU_ANO_CENSO INTEGER,
    NO_REGIAO TEXT,
    CO_REGIAO INTEGER,
    QT_MAT_BAS INTEGER,
    QT_MAT_PROF INTEGER,
    QT_MAT_EJA INTEGER,
    QT_MAT_ESP INTEGER,
    QT_MAT_FUND INTEGER,
    QT_MAT_INF INTEGER,
    QT_MAT_MED INTEGER,
    QT_MAT_ZR_NA INTEGER,
    QT_MAT_ZR_RUR INTEGER,
    QT_MAT_ZR_URB INTEGER,  -- <--- A vírgula que provavelmente faltava
    QT_MAT_TOTAL INTEGER,
    NU_RANKING INTEGER,

    PRIMARY KEY (CO_ENTIDADE, NU_ANO_CENSO)
);

CREATE TABLE tb_usuario (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nome TEXT NOT NULL,
    cpf TEXT UNIQUE NOT NULL,
    nascimento TEXT
);
